version: "3.9"

services:

  gateway:
    image: nginx:alpine
    container_name: auraflux_gateway
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - auraflux_network

  consultant:
    build:
      context: .
      dockerfile: apps/consultant/Dockerfile
    image: auraflux-consultant:latest
    container_name: auraflux_consultant
    ports:
      - "5173:5173"
    # env_file:
    #   - ./docker-var.env
    volumes:
      - ./tsconfig.base.json:/auraflux/tsconfig.base.json
      - ./.env.development:/auraflux/.env.development
      - ./apps:/auraflux/apps
      - ./packages:/auraflux/packages
      - /auraflux/apps/consultant/node_modules
    networks:
      - auraflux_network

  mull:
    build:
      context: .
      dockerfile: apps/mull/Dockerfile
    image: auraflux-mull:latest
    container_name: auraflux_mull
    ports:
      - "5174:5173"
    # env_file:
    #   - ./docker-var.env
    volumes:
      - ./tsconfig.base.json:/auraflux/tsconfig.base.json
      - ./.env.development:/auraflux/.env.development
      - ./apps:/auraflux/apps
      - ./packages:/auraflux/packages
      - /auraflux/apps/mull/node_modules
    networks:
      - auraflux_network

volumes:
  auraflux_data:

networks:
  auraflux_network:
    name: auraflux_network
    external: true
