server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://auraflux_consultant:5173/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # location /s3/ {
    #     proxy_pass http://app-domain-s3:80/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}