server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://auraflux_consultant:5173/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/project/.*mull {
        proxy_pass http://auraflux_mull:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}