<template>
  <div class="space-y-2">
    <Text tag="h3" size="lg" weight="semibold" color="gray-800">
      {{ label }}
    </Text>

    <div class="bg-gray-200 rounded-full h-2.5" role="progressbar"
      :aria-valuenow="clampedPercentage"
      aria-valuemin="0"
      aria-valuemax="100"
    >
      <BarSegment
        :width="clampedPercentage"
        :color="color"
      />
    </div>

    <Text tag="p" size="sm" :color="textColorClass" class="flex items-center space-x-2">
      <Text tag="span" weight="semibold">{{ statusLabel }}</Text>
      <Text tag="span" color="gray-500" weight="normal" size="sm">{{ description }}</Text>
    </Text>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Text from '@/components/atoms/Text.vue';
import BarSegment from '@/components/atoms/BarSegment.vue';

// --- Props ---
const props = defineProps({
  /**
   * The current completion percentage (0 to 100) for the visual bar width.
   */
  percentage: {
    type: Number,
    required: true,
    default: 0,
  },
  /**
   * The main label (e.g., "Topic Refinement Status").
   */
  label: {
    type: String,
    default: 'Status',
  },
  /**
   * The qualitative status label generated by the Agent (e.g., "Exploring").
   */
  statusLabel: {
    type: String,
    required: true,
    default: 'Awaiting Input',
  },
  /**
   * Optional descriptive text.
   */
  description: {
    type: String,
    default: 'status indicator',
  },
  /**
   * Color theme for the progress bar. Options: 'indigo', 'green', 'gray'.
   */
  color: {
    type: String as () => 'indigo' | 'green' | 'gray',
    default: 'indigo',
  },
});

// --- Computed Properties ---

/**
 * Ensures the percentage stays between 0 and 100 for safety.
 */
const clampedPercentage = computed(() => {
  return Math.max(0, Math.min(100, props.percentage));
});

/**
 * Dynamically determines the Tailwind CSS class for the descriptive text color.
 * Text color emphasizes the qualitative status based on percentage.
 */
const textColorClass = computed(() => {
  if (clampedPercentage.value > 80) {
    return 'text-green-700';
  } else if (clampedPercentage.value > 40) {
    return 'text-indigo-700';
  }
  return 'text-gray-700';
});
</script>